#! /usr/bin/env python
# encoding: utf-8

import Options

lib = bld.new_task_gen (
  features = 'cc cshlib',
  target = 'completion',
  vapi_dirs ='../../libvalide ../../libvalide/vapi ../../libvalide/libyaml-glib/src .',
  uselib = 'GIO GTK+ GMODULE GTKSOURCEVIEW VALA GTHREAD',
  uselib_local = 'valide-0.0',
  packages = 'gio-2.0 gmodule-2.0 gtk+-2.0 gtksourceview-2.0 libvala-0.12 bug_fix_completion',
  ccflags = ['-include', 'config.h', '-DG_LOG_DOMAIN="PluginCompletion"'],
  includes = '../../libvalide/libyaml-glib/libyaml/include/',
#  source = bld.path.ant_glob ('*.vala valencia-provider/*.vala
#    valencia-provider/valencia/parser.vala
#    valencia-provider/valencia/program.vala
#    valencia-provider/valencia/scanner.vala
#    valencia-provider/valencia/util.vala
#    valencia-provider/valencia/expression.vala')
  source = bld.path.ant_glob ('*.vala afrodite-provider/**/*.vala')
)

lib.install_path = bld.env['PLUGINS_DIR'] + '/' + lib.target
bld.install_files (lib.install_path, 'completion.valide-plugin')

if Options.options.debug:
  lib.env = bld.env_of_name ('debug').copy ()

